import { MiningPoolDetails } from "@/types/mining-pool";

export const mockPools: MiningPoolDetails[] = [
  {
    id: "pool-1",
    name: "US East Pool",
    hashrateTHs: 830.5,
    activeWorkers: 1240,
    rejectRate: 0.012,
    status: "online",
    last24hRevenueBTC: 0.035,
    uptimePercent: 99.82,
    location: "Ashburn, VA",
    feePercent: 1.0,
  },
  {
    id: "pool-2",
    name: "EU Central Pool",
    hashrateTHs: 460.3,
    activeWorkers: 876,
    rejectRate: 0.045,
    status: "degraded",
    last24hRevenueBTC: 0.028,
    uptimePercent: 95.43,
    location: "Frankfurt, DE",
    feePercent: 1.2,
  },
  {
    id: "pool-3",
    name: "Asia Pacific Pool",
    hashrateTHs: 120.8,
    activeWorkers: 234,
    rejectRate: 0.089,
    status: "offline",
    last24hRevenueBTC: 0.012,
    uptimePercent: 88.91,
    location: "Singapore",
    feePercent: 1.5,
  },
  {
    id: "pool-4",
    name: "Canada West Pool",
    hashrateTHs: 650.2,
    activeWorkers: 1050,
    rejectRate: 0.023,
    status: "online",
    last24hRevenueBTC: 0.031,
    uptimePercent: 99.95,
    location: "Vancouver, BC",
    feePercent: 0.9,
  },
];
